#!/bin/bash
#############################
#SBATCH -J vasp
#SBATCH -N 1              
#SBATCH -p vasp
#SBATCH --qos=debug 
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24         
#SBATCH -o %x-%j.sout
#SBATCH -e %x-%j.serr
#SBATCH -D .
#############################

source /opt/intel2020/compilers_and_libraries/linux/bin/compilervars.sh intel64 
source /opt/intel2020/mkl/bin/mklvars.sh intel64
source /opt/intel2020/impi/2019.9.304/intel64/bin/mpivars.sh intel64
#export PATH=$PATH:/home/share/software/vasp/intel20vasp630 
export PATH=/home/share/software/vtstvasp630:$PATH
export PATH=/home/share/software/vasp/vtstscripts-957:$PATH 

ulimit -s unlimited
pkill -f vasp*
#export UCX_TLS=tcp
#export FI_PROVIDER=verbs

#export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
#mpirun -n $SLURM_NTASKS vasp_std 
#python v1r2.py cip.dat  >krr_cip.log 
#python v1r2.py  picip.dat >krrpicip.log
#date

python v0r2.py piangle3d > v0r2.piangle3d.log 
